name: build bpi-r4-std image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: master
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  CUSTOM_FEEDS_SH: ${{ github.workspace }}/custom-feeds.sh
  CUSTOM_PACKAGES_SH: ${{ github.workspace }}/custom-packages.sh
  CUSTOM_CONFIG_SH: ${{ github.workspace }}/custom-config.sh
  TZ: Europe/Berlin
  DEVICE_NAME: unknown
  FILE_DATE: unknown
  FIRMWARE: unknown

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: openwrt/sdk:latest
      options: --user root --workdir /github/workspace --privileged
    env:
      FORCE_UNSAFE_CONFIGURE: "1"
      CCACHE_DIR: /github/workspace/ccache

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: openwrt-ccache-${{ github.sha }}
        restore-keys: openwrt-ccache-
        max-size: 1G

    - name: Cache OpenWrt sources
      id: cache-openwrt-sources
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BUILD_ROOT }}/dl
          ${{ env.BUILD_ROOT }}/staging_dir/host/ccache
        key: openwrt-dl-${{ hashFiles('openwrt/feeds.conf.default') }}

    - name: Show if source cache hit
      run: echo "Cache hit: ${{ steps.cache-openwrt-sources.outputs.cache-hit }}"

    - name: Download the sources
      run: git clone --branch $REPO_BRANCH $REPO_URL $BUILD_ROOT

    - name: Auto select stable revision
      id: autoselect
      if: github.event.client_payload.version == 'stable'
      run: |
        cd $BUILD_ROOT && git checkout $(git tag --sort=-creatordate | head -n1)
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Manual select version
      id: manualselect
      if: github.event.inputs.version != null && github.event.inputs.version != 'snapshot'
      run: |
        cd $BUILD_ROOT && git checkout ${{ github.event.inputs.version }}
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Load custom configurations
      run: |
        chmod +x custom-*.sh
        $CUSTOM_FEEDS_SH
        $BUILD_ROOT/scripts/feeds update -a && $BUILD_ROOT/scripts/feeds install -a
        $CUSTOM_PACKAGES_SH
        $CUSTOM_CONFIG_SH

    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      if: github.event.inputs.ssh == 'true'

    - name: Build firmware
      id: compile
      run: |
        cd $BUILD_ROOT
        echo "Using $(nproc) threads for compilation"
        make -j$(nproc) defconfig download world || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Show ccache stats
      run: ccache -s

    - name: Upload bin directory
      uses: actions/upload-artifact@v4
      if: steps.compile.outputs.status == 'success'
      with:
        name: OpenWrt_bin_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.BUILD_ROOT }}/bin

    - name: Organize files
      id: organize
      run: |
        cd $BUILD_ROOT/bin/targets/*/* && rm -rf packages
        { echo '### SHA256SUMS'; echo '```txt'; cat sha256sums; echo '```'; } > $BUILD_ROOT/SHA256SUMS
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success'
      with:
        name: OpenWrt_firmware_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      run: |
        if [[ "${{ github.event.inputs.version }}" == "snapshot" ]]; then
          echo "release_tag=SNAPSHOT_$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        else
          echo "release_tag=$(cd $BUILD_ROOT && git describe --tags --abbrev=0)_$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        fi
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ env.FIRMWARE }}/*
        body_path: ${{ env.BUILD_ROOT }}/SHA256SUMS

    - name: Cleanup old runs
      if: always()
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 30
        keep_minimum_runs: 5

    - name: Remove old releases
      if: always()
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
